name: house_price_prediction_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - openjdk=21
  - pip
  - nodejs
  - julia
  - octave
  - r
  - octave_kernel
  - r-essentials
  - r-base
  - r-irkernel
  - r-microbenchmark
  - radian
  - rchitect
  - r-islr2
  - r-leaps
  - r-tree
  - r-car
  - r-torch
  - r-keras
  - r-gbm
  - r-zeallot
  - r-pls
  - r-matrix
  - r-e1071
  - r-gam
  - r-glmnet
  - r-mass
  - r-akima
  - r-survival
  - r-bart
  - r-class
  - r-randomForest
  - r-rocr
  - r-splines2
  - r-jpeg
  - r-boot
  - r-interp
  - r-ggplot2
  - r-cli
  - r-dplyr
  - r-magrittr
  - r-purrr
  - r-rlang
  - r-tidyselect
  - r-tidyr
  - r-stringr
  - r-tibble
  - r-reticulate
  - r-crosstalk
  - r-plotly
  - r-renv
  - r-devtools
  - r-pdftools
  - r-forge
  - r-tfestimators
  - r-tfdatasets
  - r-rjava
  - r-xgboost
  - r-xgboost-cpu
  - pytest
  - pytest-cov
  - coverage
  - numpy
  - pandas
  - pandas-datareader
  - scipy
  - plotly
  - kaleido-core
  - python-kaleido
  - numba
  - numexpr
  - statsmodels
  - matplotlib-base
  - matplotlib
  - requests
  - requests-file
  - requests-toolbelt
  - scrapy
  - networkx
  - setuptools
  - libsqlite
  - sqlite
  - mysql
  - mysql-common
  - mysql-libs
  - scikit-learn
  - scikit-image
  - sklearn-pandas
  - pillow
  - seaborn-base
  - seaborn
  - line_profiler
  - memory_profiler
  - uritools
  - xtensor
  - xarray
  - jaxlib
  - jax
  - pywavelets
  - pyarrow
  - graph-tool
  - slycot
  - control
  - python-igraph
  - bokeh
  - sympy
  - mpld3
  - pyopencl
  - libopencv
  - opencv
  - py-opencv
  - brotli
  - brotlipy
  - zlib
  - bzip2
  - aiohttp
  - xz
  - jq
  - lz4
  - libcurl
  - curl
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - pandoc
  - nbformat
  - nbdime
  - yaml
  - protobuf
  - mathjax
  - katex
  - poppler
  - poppler-data
  - texlive-core
  - graphviz
  - pygraphviz
  - python-graphviz
  - pydot
  - ipykernel
  - ipython
  - ipywidgets
  - qtconsole
  - jupyter
  - jupyter_core
  - jupyter_client
  - jupyter_console
  - jupyter_server
  - jupyterlab
  - jupyterlab_server
  - notebook
  - pyqt
  - widgetsnbextension
  - ipympl
  - ipython_genutils
  - ffmpeg
  - joblib
  - tqdm
  - Lightgbm
  - catboost
  - nltk
  - py-xgboost
  - py-xgboost-cpu
  - xgboost
  - libxgboost
  - keras
  - keras-core
  - keras-tuner
  - keras-preprocessing
  - keras-cv
  - keras-applications
  - tensorboard
  - tensorflow-datasets
  - tensorflow
  - tensorflow-cpu
  - tensorflow-metadata
  - transformers
  - gymnasium
  - pytorch
  - torchvision
  - flax
  - pyarrow-core
  - mypy
  - python-lsp-server
  - rpy2
  - pymc
  - shap
